cloud:
  aws:
    credentials:


    region:
      static: eu-west-1
    end-point:
      uri: https://s3-website-eu-west-1.amazonaws.com
    stack:
      auto: false

application:
  bucket:
    name: learner-support-center


server:
  port:9090
